export const specialIPv4Content = {
  title: 'Special-Use IPv4 Blocks (RFC 6890)',
  description: 'Complete reference of reserved IPv4 address blocks and their specific purposes.',

  ranges: [
    {
      network: '0.0.0.0/8',
      purpose: 'This host on this network',
      rfc: 'RFC 1122',
      routable: false,
      description: 'Used for default routes and unspecified addresses',
    },
    {
      network: '10.0.0.0/8',
      purpose: 'Private-Use Networks',
      rfc: 'RFC 1918',
      routable: false,
      description: 'Private addresses for internal networks (Class A)',
    },
    {
      network: '100.64.0.0/10',
      purpose: 'Shared Address Space (CGNAT)',
      rfc: 'RFC 6598',
      routable: false,
      description: 'Carrier-Grade NAT, ISP shared addressing',
    },
    {
      network: '127.0.0.0/8',
      purpose: 'Loopback',
      rfc: 'RFC 1122',
      routable: false,
      description: 'localhost addresses, typically 127.0.0.1',
    },
    {
      network: '169.254.0.0/16',
      purpose: 'Link Local (APIPA)',
      rfc: 'RFC 3927',
      routable: false,
      description: 'Auto-assigned when DHCP fails',
    },
    {
      network: '172.16.0.0/12',
      purpose: 'Private-Use Networks',
      rfc: 'RFC 1918',
      routable: false,
      description: 'Private addresses for internal networks (Class B)',
    },
    {
      network: '192.0.0.0/24',
      purpose: 'IETF Protocol Assignments',
      rfc: 'RFC 6890',
      routable: true,
      description: 'Special protocol use, some addresses globally routable',
    },
    {
      network: '192.0.2.0/24',
      purpose: 'TEST-NET-1',
      rfc: 'RFC 5737',
      routable: false,
      description: 'Documentation and example code',
    },
    {
      network: '192.88.99.0/24',
      purpose: '6to4 Relay Anycast',
      rfc: 'RFC 3068',
      routable: true,
      description: 'IPv6 to IPv4 relay (deprecated)',
    },
    {
      network: '192.168.0.0/16',
      purpose: 'Private-Use Networks',
      rfc: 'RFC 1918',
      routable: false,
      description: 'Private addresses for internal networks (Class C)',
    },
    {
      network: '198.18.0.0/15',
      purpose: 'Network Interconnect Device Benchmark Testing',
      rfc: 'RFC 2544',
      routable: false,
      description: 'Performance testing between network devices',
    },
    {
      network: '198.51.100.0/24',
      purpose: 'TEST-NET-2',
      rfc: 'RFC 5737',
      routable: false,
      description: 'Documentation and example code',
    },
    {
      network: '203.0.113.0/24',
      purpose: 'TEST-NET-3',
      rfc: 'RFC 5737',
      routable: false,
      description: 'Documentation and example code',
    },
    {
      network: '224.0.0.0/4',
      purpose: 'Multicast',
      rfc: 'RFC 1112',
      routable: true,
      description: 'IPv4 multicast addresses',
    },
    {
      network: '240.0.0.0/4',
      purpose: 'Reserved for Future Use',
      rfc: 'RFC 1112',
      routable: false,
      description: 'Reserved block, not usable',
    },
    {
      network: '255.255.255.255/32',
      purpose: 'Limited Broadcast',
      rfc: 'RFC 919',
      routable: false,
      description: 'Broadcast to all hosts on local network',
    },
  ],

  categories: {
    private: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'],
    testing: ['192.0.2.0/24', '198.51.100.0/24', '203.0.113.0/24'],
    special: ['127.0.0.0/8', '169.254.0.0/16', '224.0.0.0/4'],
    cgnat: ['100.64.0.0/10'],
  },

  quickTips: [
    'Private addresses (10.x, 172.16-31.x, 192.168.x) never appear on the public internet',
    '100.64.x.x means your ISP is using Carrier-Grade NAT',
    '169.254.x.x means DHCP failed and the device auto-configured',
    'TEST-NET addresses are safe to use in documentation',
    '224.x.x.x and above are multicast or reserved',
    "Never use 240.x.x.x - it's reserved and may not work",
  ],
};
