import { resolve } from '$app/paths';
import { site, author, license as _license } from '$lib/constants/site';
import { extractAllNavItems } from '$lib/utils/nav-helpers';

// Helper function to create paths with base path support
function makePath(path: string): string {
  return resolve(path as any) || path;
}

export type NavItem = {
  href: string;
  label: string;
  description?: string;
  icon?: string;
  keywords?: string[];
  featured?: boolean;
};

export type NavGroup = {
  title: string;
  description?: string;
  items: NavItem[];
};

// Individual standalone pages
export const STANDALONE_PAGES: NavItem[] = [
  {
    href: makePath('/bookmarks'),
    label: 'Bookmarks',
    icon: 'bookmarks',
    description: 'Save and organize network calculations and tool results',
    keywords: ['bookmarks', 'saved', 'favorites', 'shortcuts', 'calculations'],
  },
  {
    href: makePath('/search'),
    label: 'Search',
    icon: 'search',
    description: 'Find tools and reference content quickly',
    keywords: ['search', 'find', 'lookup', 'tools', 'reference', 'content'],
  },
  {
    href: makePath('/settings'),
    label: 'Settings',
    icon: 'settings2',
    description: 'Customize themes, layouts, and accessibility preferences',
    keywords: ['settings', 'preferences', 'theme', 'layout', 'accessibility', 'customize'],
  },
  // {
  //   href: makePath('/offline'),
  //   label: 'Offline',
  //   description: 'Access cached tools and data offline',
  //   keywords: ['offline', 'cache', 'no-internet', 'local'],
  //   icon: 'offline',
  // },
];

export const TOP_NAV: NavItem[] = [
  {
    href: makePath('/subnetting'),
    label: 'Subnetting',
    description: 'Subnet calculators for IPv4, IPv6, VLSM, supernetting',
    keywords: ['subnet calculator', 'ipv4 ipv6 subnetting', 'vlsm', 'network planning', 'netmask calculator'],
  },
  {
    href: makePath('/cidr'),
    label: 'CIDR',
    description: 'CIDR notation tools, converters, and calculators',
    keywords: ['cidr notation', 'subnet mask converter', 'cidr summarizer', 'set operations', 'ip blocks'],
  },
  {
    href: makePath('/ip-address-convertor'),
    label: 'IP Tools',
    description: 'IP address converters, validators, and generators',
    keywords: ['ip converter', 'address validator', 'ipv4 ipv6 tools', 'ip format', 'address generator'],
  },
  {
    href: makePath('/dns'),
    label: 'DNS Tools',
    description: 'DNS record generators, validators, and DNSSEC tools',
    keywords: ['dns records', 'zone files', 'dnssec', 'ptr reverse', 'spf dmarc dkim'],
  },
  {
    href: makePath('/dhcp'),
    label: 'DHCP',
    description: 'DHCP option generators for wireless controllers and network configuration',
    keywords: ['dhcp options', 'vendor specific', 'wireless controller', 'cisco aruba ruckus', 'ap discovery'],
  },
  {
    href: makePath('/diagnostics'),
    label: 'Lookups',
    description: 'Network diagnostics and connectivity testing',
    keywords: ['dns lookup', 'http headers', 'tls certificate', 'network diagnostics', 'port check'],
  },
  {
    href: makePath('/reference'),
    label: 'Ref',
    description: 'Networking reference guides and lookup tables',
    keywords: [
      'reference',
      'guide',
      'explanation',
      'networking',
      'fundamentals',
      'cidr',
      'vlsm',
      'ipv6',
      'dns',
      'protocols',
      'ports',
      'asn',
      'icmp',
      'arp',
      'ndp',
      'multicast',
      'private',
      'public',
    ],
  },
];

// Sections that have sub-pages (drives the conditional SubHeader)
export const SUB_NAV: Record<string, (NavItem | NavGroup)[]> = {
  '/subnetting': [
    {
      href: makePath('/subnetting/ipv4-subnet-calculator'),
      label: 'IPv4 Subnet Calculator',
      description: 'Calculate subnet masks, network addresses, broadcast addresses, and host ranges',
      icon: 'subnet-calculator',
      featured: true,
      keywords: ['ipv4 subnet', 'subnet calculator', 'netmask', 'broadcast address', 'usable hosts', 'cidr notation'],
    },
    {
      href: makePath('/subnetting/ipv6-subnet-calculator'),
      label: 'IPv6 Subnet Calculator',
      description: 'Calculate IPv6 subnets and network prefixes',
      icon: 'ipv6-subnet-calculator',
      keywords: ['ipv6 subnet', 'prefix calculator', '128-bit', 'ipv6 addressing', 'subnet prefix'],
    },
    {
      href: makePath('/subnetting/vlsm-calculator'),
      label: 'VLSM Calculator',
      description: 'Variable Length Subnet Mask calculator for splitting networks into smaller subnets',
      icon: 'vlsm-calculator',
      keywords: ['vlsm', 'variable length subnet', 'subnet allocation', 'network design', 'vlsm calculator'],
    },
    {
      href: makePath('/subnetting/supernet-calculator'),
      label: 'Supernet Calculator',
      description: 'Aggregate multiple networks into supernets for route summarization',
      icon: 'supernet-calculator',
      keywords: ['supernet', 'route summarization', 'aggregate networks', 'supernetting'],
    },
    {
      href: makePath('/subnetting/planner'),
      label: 'Subnet Planner',
      description: 'Design VLSM networks with drag-and-drop planning',
      icon: 'subnet-planner',
      keywords: ['subnet planner', 'network design', 'vlsm planning', 'visual allocation'],
    },
  ],
  '/cidr': [
    {
      href: makePath('/cidr/mask-converter'),
      title: 'CIDR Masks',
      description: 'Convert between CIDR notation and subnet masks',
      items: [
        {
          href: makePath('/cidr/mask-converter/cidr-to-subnet-mask'),
          label: 'CIDR → Mask',
          description: 'Convert CIDR notation (e.g. /24) to subnet mask format (255.255.255.0)',
          icon: 'cidr-convertor',
          featured: true,
          keywords: ['cidr notation', 'subnet mask', 'cidr to mask', '/24', '255.255.255.0', 'netmask conversion'],
        },
        {
          href: makePath('/cidr/mask-converter/subnet-mask-to-cidr'),
          label: 'Mask → CIDR',
          description: 'Convert subnet mask format (255.255.255.0) to CIDR notation (/24)',
          icon: 'cidr-convertor-mask',
          keywords: ['subnet mask', 'cidr notation', 'mask to cidr', '/24', '255.255.255.0', 'netmask conversion'],
        },
      ],
    },
    {
      href: makePath('/cidr/range-to-cidr'),
      label: 'IP Range to CIDR',
      description: 'Convert IP address ranges (start-end) into minimal CIDR blocks',
      icon: 'sliders',
      keywords: ['ip range', 'cidr blocks', 'range to cidr', 'start end', 'firewall rules', 'acl conversion'],
    },
    {
      href: makePath('/cidr/summarize'),
      label: 'CIDR Summarizer',
      description: 'Optimize mixed IP addresses, CIDR blocks, and ranges into minimal CIDR prefixes',
      icon: 'cidr-summarize',
      keywords: ['cidr summarization', 'optimize blocks', 'aggregate prefixes', 'minimal cidr', 'route aggregation'],
    },
    {
      href: makePath('/cidr/split'),
      label: 'CIDR Split',
      description: 'Split a network into N equal child subnets or to a target prefix length',
      icon: 'subnet-splitter',
      keywords: ['cidr split', 'subnet division', 'split network', 'child subnets', 'prefix length'],
    },
    {
      href: makePath('/cidr/next-available'),
      label: 'Next Available Subnet',
      description: 'Find available subnets in pools using first-fit or best-fit algorithms',
      icon: 'next-available-subnet',
      keywords: ['next available', 'find subnet', 'subnet pools', 'first-fit', 'best-fit', 'ip allocation'],
    },
    {
      href: makePath('/cidr/gaps'),
      label: 'Free Space Finder',
      description: 'List unallocated IP blocks in CIDR pools by prefix length',
      icon: 'cidr-gaps',
      keywords: ['free space', 'cidr gaps', 'unallocated blocks', 'ip pools', 'available ranges'],
    },
    {
      href: makePath('/cidr/deaggregate'),
      label: 'CIDR Deaggregate',
      description: 'Break CIDR blocks into smaller uniform subnets (e.g., split into /24s)',
      icon: 'cidr-deaggregate',
      keywords: ['cidr deaggregate', 'break down', 'uniform subnets', 'decompose blocks', 'split cidr'],
    },
    {
      href: makePath('/cidr/compare'),
      label: 'CIDR Compare',
      description: 'Compare CIDR lists to show added, removed, and unchanged blocks',
      icon: 'cidr-compare',
      keywords: ['cidr compare', 'cidr diff', 'compare lists', 'audit changes', 'added removed'],
    },
    {
      href: makePath('/cidr/allocator'),
      label: 'CIDR Allocator',
      description: 'Allocate subnets into network pools using first-fit or best-fit algorithms',
      icon: 'cidr-allocator',
      keywords: ['cidr allocator', 'bin packing', 'first-fit', 'best-fit', 'subnet allocation'],
    },
    {
      href: makePath('/cidr/alignment'),
      label: 'CIDR Alignment',
      description: 'Check if IP addresses align to CIDR prefix boundaries',
      icon: 'cidr-alignment',
      keywords: ['cidr alignment', 'boundary check', 'prefix boundaries', 'address alignment', 'subnet efficiency'],
    },
    {
      href: makePath('/cidr/wildcard-mask'),
      label: 'Wildcard Mask Converter',
      description: 'Convert between CIDR, subnet masks, and wildcard masks with ACL rule generation',
      icon: 'wildcard-mask',
      keywords: ['wildcard mask', 'inverse mask', 'acl rules', 'cisco acl', 'juniper acl', 'access control'],
    },
    {
      href: makePath('/cidr/set-operations'),
      title: 'Set Operations',
      items: [
        {
          href: makePath('/cidr/set-operations/diff'),
          label: 'Difference (A - B)',
          description: 'Subtract CIDR blocks, ranges, and IPs from another set',
          icon: 'diff',
          keywords: ['set difference', 'subtract cidr', 'exclude ranges', 'cidr math', 'ip exclusion'],
        },
        {
          href: makePath('/cidr/set-operations/overlap'),
          label: 'Overlap (A ∩ B)',
          description: 'Find overlapping IPs and ranges between two sets',
          icon: 'intersection',
          keywords: ['set intersection', 'cidr overlap', 'ip collision', 'conflict detection', 'shared ranges'],
        },
        {
          href: makePath('/cidr/set-operations/contains'),
          label: 'Contains (A ⊆ B)',
          description: 'Check if one IP set contains another',
          icon: 'containment',
          featured: true,
          keywords: ['set containment', 'subset check', 'superset analysis', 'cidr hierarchy', 'ip inclusion'],
        },
      ],
    },
  ],
  '/ip-address-convertor': [
    {
      title: 'Number Formats',
      items: [
        {
          href: makePath('/ip-address-convertor/representations'),
          label: 'Format Representations',
          description: 'Convert IP addresses between decimal, binary, hexadecimal, and octal number systems',
          icon: 'ip-convertor',
          keywords: ['ip formats', 'decimal to binary', 'hex conversion', 'octal notation', 'number systems'],
        },
      ],
    },
    {
      title: 'Address Calculations',
      items: [
        {
          href: makePath('/ip-address-convertor/distance'),
          label: 'IP Distance Calculator',
          description: 'Calculate the number of addresses between two IPs with inclusive/exclusive counting',
          icon: 'ip-distance',
          keywords: ['ip distance', 'count addresses', 'address range', 'ip spacing', 'between ips'],
        },
        {
          href: makePath('/ip-address-convertor/nth-ip'),
          label: 'Nth IP Calculator',
          description: 'Resolve the IP address at a specific index within networks and ranges with offset support',
          icon: 'nth-ip',
          keywords: ['nth ip', 'ip at index', 'address offset', 'ip position', 'host enumeration'],
        },
        {
          href: makePath('/ip-address-convertor/random'),
          label: 'Random IP Generator',
          description: 'Generate random IP addresses from networks with uniqueness control and seeded randomness',
          icon: 'random-ip',
          keywords: ['random ip', 'generate ips', 'random addresses', 'seeded random', 'ip generator'],
        },
        {
          href: makePath('/ip-address-convertor/regex'),
          label: 'IP Regex Generator',
          description:
            'Generate safe regular expressions for matching IPv4 and IPv6 addresses with customizable validation options',
          icon: 'ip-regex-generator',
          keywords: ['ip regex', 'regex pattern', 'ip validation regex', 'address matching', 'regexp generator'],
        },
        {
          href: makePath('/ip-address-convertor/validator'),
          label: 'IP Address Validator',
          description: 'Validate IPv4 and IPv6 addresses with detailed error analysis and format checking',
          icon: 'ip-validator',
          keywords: ['ip validation', 'validate address', 'check ip', 'verify ip', 'address checker'],
        },
        {
          href: makePath('/ip-address-convertor/enumerate'),
          label: 'IP Enumerate',
          description: 'Safely enumerate all IP addresses in CIDR blocks and ranges with CSV/JSON export',
          icon: 'ip-enumerate',
          keywords: ['ip enumeration', 'list ips', 'generate list', 'export ips', 'csv json export'],
        },
      ],
    },
    {
      title: 'IPv6 Notation',
      items: [
        {
          href: makePath('/ip-address-convertor/notation/ipv6-expand'),
          label: 'IPv6 Expand',
          description: 'Expand compressed IPv6 addresses to full 128-bit hexadecimal format',
          icon: 'ipv6-expand',
          keywords: ['ipv6 expand', 'full format', 'uncompress ipv6', '128-bit', 'double colon'],
        },
        {
          href: makePath('/ip-address-convertor/notation/ipv6-compress'),
          label: 'IPv6 Compress',
          description: 'Compress expanded IPv6 addresses using :: notation and removing leading zeros',
          icon: 'ipv6-compress',
          keywords: ['ipv6 compress', 'shorten ipv6', 'compact format', 'double colon', 'remove zeros'],
        },
        {
          href: makePath('/ip-address-convertor/notation/normalize'),
          label: 'IPv6 Normalizer',
          description: 'Normalize IPv6 addresses to RFC 5952 canonical form with step-by-step transformation',
          icon: 'ip-normalize',
          keywords: ['ipv6 normalize', 'canonical form', 'rfc 5952', 'standard format', 'consistent notation'],
        },
        {
          href: makePath('/ip-address-convertor/notation/zone-id'),
          label: 'IPv6 Zone ID Handler',
          description: 'Process IPv6 addresses with zone identifiers for link-local and multicast addresses',
          icon: 'zone-id-handler',
          keywords: ['ipv6 zone id', 'link-local', 'scope identifier', 'fe80', 'scoped address'],
        },
        {
          href: makePath('/ip-address-convertor/ipv6/solicited-node'),
          label: 'IPv6 Solicited-Node',
          description: 'Compute solicited-node multicast addresses from IPv6 unicast for Neighbor Discovery Protocol',
          icon: 'ipv6-solicited-node',
          keywords: ['solicited-node', 'multicast address', 'ndp', 'neighbor discovery', 'ff02::1:ff'],
        },
        {
          href: makePath('/ip-address-convertor/ipv6/teredo'),
          label: 'IPv6 Teredo Parser',
          description:
            'Parse Teredo IPv6 addresses to extract server IPv4, flags, mapped port, and client IPv4 components',
          icon: 'ipv6-teredo',
          keywords: ['teredo', 'ipv6 tunnel', '2001:0000', 'parse teredo', 'tunnel components'],
        },
        {
          href: makePath('/ip-address-convertor/ipv6/nat64'),
          label: 'IPv6 NAT64 Translator',
          description: 'Translate between IPv4 and IPv6 addresses using NAT64 prefix (64:ff9b::/96 or custom)',
          icon: 'ipv6-nat64',
          keywords: ['nat64', 'ipv4 ipv6 translation', '64:ff9b', 'nat64 prefix', 'ip translation'],
        },
      ],
    },
    {
      title: 'IP Families',
      items: [
        {
          href: makePath('/ip-address-convertor/families/ipv4-to-ipv6'),
          label: 'IPv4 → IPv6',
          description: 'Convert IPv4 addresses to IPv6 format using IPv4-mapped IPv6 addressing',
          icon: 'ipv4-ipv6',
          keywords: ['ipv4 to ipv6', 'ipv4-mapped', 'dual-stack', '::ffff', 'address embedding'],
        },
        {
          href: makePath('/ip-address-convertor/families/ipv6-to-ipv4'),
          label: 'IPv6 → IPv4',
          description: 'Extract IPv4 addresses from IPv4-mapped IPv6 addresses',
          icon: 'ipv6-ipv4',
          keywords: ['ipv6 to ipv4', 'extract ipv4', 'ipv4-mapped', '::ffff', 'reverse conversion'],
        },
      ],
    },
    {
      title: 'Address Generation',
      items: [
        {
          href: makePath('/ip-address-convertor/eui64'),
          label: 'EUI-64 Converter',
          description: 'Convert between MAC addresses and IPv6 EUI-64 interface identifiers with IPv6 generation',
          icon: 'eui64-converter',
          keywords: ['eui-64', 'mac to ipv6', 'slaac', 'interface identifier', 'auto-configuration'],
        },
        {
          href: makePath('/ip-address-convertor/ula-generator'),
          label: 'ULA Generator',
          description: 'Generate RFC 4193 Unique Local Addresses with cryptographically secure Global IDs',
          icon: 'ula-generator',
          keywords: ['ula', 'unique local address', 'rfc 4193', 'fc00 fd00', 'private ipv6'],
        },
        {
          href: makePath('/ip-address-convertor/mac-address'),
          label: 'MAC Address Converter',
          description: 'Convert MAC addresses between formats and identify manufacturer from OUI database',
          icon: 'mac-lookup',
          featured: true,
          keywords: ['mac address', 'oui lookup', 'manufacturer', 'mac format', 'cisco notation', 'vendor lookup'],
        },
      ],
    },
  ],
  '/dhcp': [
    {
      title: 'DHCPv4 Options',
      description: 'DHCPv4 option generators and builders',
      items: [
        {
          href: makePath('/dhcp/v4/options/option3-default-gateway'),
          label: 'Option 3 - Default Gateway',
          description:
            'Build and decode DHCP default gateway configuration with support for multiple gateways and subnet validation',
          icon: 'router',
          keywords: [
            'option 3',
            'default gateway',
            'router',
            'gateway configuration',
            'multiple gateways',
            'gateway redundancy',
            'failover',
            'routing',
            'dhcp gateway',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/options6-15-dns'),
          label: 'Options 6/15 - DNS & Domain',
          description: 'Build and decode DNS server and domain name options for complete DNS configuration',
          icon: 'dns',
          keywords: [
            'option 6',
            'option 15',
            'dns servers',
            'domain name',
            'nameservers',
            'dns configuration',
            'hostname resolution',
            'dhcp dns',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option51-lease-time'),
          label: 'Option 51 - Lease Time',
          description: 'Build and decode lease time option with automatic T1/T2 renewal timer calculations',
          icon: 'timeline',
          keywords: [
            'option 51',
            'lease time',
            'ip lease',
            't1 timer',
            't2 timer',
            'renewal',
            'rebinding',
            'infinite lease',
            'dhcp lease duration',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option43-vendor-specific'),
          label: 'Option 43 - Vendor Specific',
          description: 'Generate DHCP Option 43 for wireless controller discovery (Cisco, Aruba, Ruckus, UniFi)',
          icon: 'router',
          featured: true,
          keywords: [
            'option 43',
            'vendor specific',
            'wireless controller',
            'wlc discovery',
            'cisco wlc',
            'aruba controller',
            'ruckus controller',
            'unifi controller',
            'ap discovery',
            'capwap',
            'access point provisioning',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option60-vendor-class'),
          label: 'Option 60 - Vendor Class',
          description:
            'Build vendor class identifiers for DHCP class-based policies (ISC, Kea, Windows, dnsmasq, MikroTik)',
          icon: 'tools',
          keywords: [
            'option 60',
            'vendor class',
            'vendor identifier',
            'vci',
            'class-based policy',
            'dhcp classes',
            'pxe boot',
            'vendor matching',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option61-clientid'),
          label: 'Option 61 - Client ID',
          description:
            'Build and decode DHCPv4 Client Identifier: hardware type + MAC address or arbitrary opaque data per RFC 2132',
          icon: 'id-card',
          keywords: [
            'option 61',
            'client identifier',
            'client id',
            'hardware type',
            'mac address',
            'opaque data',
            'dhcp client id',
            'rfc 2132',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option82-relay-agent'),
          label: 'Option 82 - Relay Agent',
          description: 'Construct and parse DHCP Relay Agent Information with Circuit-ID, Remote-ID, and VLAN formats',
          icon: 'tools',
          keywords: [
            'option 82',
            'relay agent',
            'relay information',
            'circuit id',
            'remote id',
            'vlan tagging',
            'suboption',
            'dhcp relay',
            'agent information',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option119-domain-search'),
          label: 'Option 119 - Domain Search',
          description:
            'Encode and decode Domain Search List (RFC 3397/6731) to/from RFC 1035 wire format with domain compression',
          icon: 'globe',
          keywords: [
            'option 119',
            'domain search',
            'search list',
            'dns suffix',
            'domain compression',
            'wire format',
            'rfc 3397',
            'dns search domains',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option121-classless-routes'),
          label: 'Option 121/249 - Classless Routes',
          description:
            'Encode and decode Classless Static Routes (RFC 3442 / MSFT 249) with bit-packed network prefixes for routing configuration',
          icon: 'compass',
          keywords: [
            'option 121',
            'option 249',
            'classless routes',
            'static routes',
            'route configuration',
            'rfc 3442',
            'microsoft routes',
            'bit-packed routes',
            'custom routing',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/option150-tftp-server'),
          label: 'Options 150/66/67 - TFTP Server',
          description:
            'Configure TFTP servers for PXE boot and Cisco IP phones with Option 150 (TFTP list), Option 66 (server name), and Option 67 (bootfile)',
          icon: 'server',
          keywords: [
            'option 150',
            'option 66',
            'option 67',
            'tftp server',
            'pxe boot',
            'cisco phones',
            'bootfile',
            'next-server',
            'network boot',
            'uefi boot',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/pxe-boot-profile'),
          label: 'PXE Boot Profile',
          description:
            'Generate PXE boot profiles with automatic UEFI/BIOS detection using Options 93/94 for architecture-aware bootfile selection',
          icon: 'tools',
          keywords: [
            'pxe boot',
            'boot profile',
            'uefi',
            'bios',
            'architecture detection',
            'option 93',
            'option 94',
            'bootfile selection',
            'ipxe',
            'windows deployment',
            'network boot',
          ],
        },
        {
          href: makePath('/dhcp/v4/options/freeform-tlv'),
          label: 'Freeform TLV Composer',
          description:
            'Build custom DHCP options using Type-Length-Value encoding with support for IPv4, IPv6, FQDN, strings, hex data, and numeric types',
          icon: 'tools',
          keywords: [
            'tlv',
            'type length value',
            'custom option',
            'freeform option',
            'option builder',
            'hex encoding',
            'vendor option',
            'site-specific',
            'dhcp tlv',
          ],
        },
      ],
    },
    {
      title: 'DHCPv6 Options',
      description: 'DHCPv6 option generators and configuration tools',
      items: [
        {
          href: makePath('/dhcp/v6/options/option23-24-dns'),
          label: 'Options 23/24 - DNS Servers & Search',
          description:
            'Configure DNS servers (Option 23) and search domains (Option 24) for DHCPv6 clients per RFC 3646',
          icon: 'globe',
          keywords: [
            'option 23',
            'option 24',
            'dhcpv6 dns',
            'recursive dns',
            'dns servers',
            'search domains',
            'rfc 3646',
            'ipv6 dns',
            'slaac',
          ],
        },
        {
          href: makePath('/dhcp/v6/options/option25-prefix-delegation'),
          label: 'Options 25/26 - Prefix Delegation',
          description:
            'Build DHCPv6 IA_PD options for delegating IPv6 prefixes to requesting routers with IA Prefix options per RFC 8415',
          icon: 'share',
          keywords: [
            'option 25',
            'option 26',
            'prefix delegation',
            'ia_pd',
            'ipv6 pd',
            'delegated prefix',
            'isp delegation',
            'rfc 8415',
            'iaid',
          ],
        },
        {
          href: makePath('/dhcp/v6/options/option39-fqdn'),
          label: 'Option 39 - Client FQDN',
          description:
            'Configure Client FQDN Option for DHCPv6 dynamic DNS updates with S, O, and N flags per RFC 4704',
          icon: 'globe',
          keywords: [
            'option 39',
            'client fqdn',
            'fully qualified domain',
            'hostname',
            'ddns',
            'dynamic dns',
            'rfc 4704',
            'fqdn flags',
            'dhcpv6 fqdn',
          ],
        },
      ],
    },
    {
      title: 'DHCPv6 Identity',
      description: 'DHCPv6 client identity and association identifier tools',
      items: [
        {
          href: makePath('/dhcp/v6/identity/duid-generator'),
          label: 'DUID Generator',
          description:
            'Generate DHCP Unique Identifiers (DUID) for DHCPv6 clients: DUID-LLT, DUID-EN, DUID-LL, and DUID-UUID per RFC 8415',
          icon: 'something',
          keywords: [
            'duid',
            'dhcp unique identifier',
            'duid-llt',
            'duid-en',
            'duid-ll',
            'duid-uuid',
            'client identifier',
            'rfc 8415',
            'dhcpv6 identity',
          ],
        },
        {
          href: makePath('/dhcp/v6/identity/iaid-calculator'),
          label: 'IAID Calculator',
          description:
            'Calculate Identity Association Identifier (IAID) for DHCPv6 interfaces from index, name, or MAC address with OS-specific conventions',
          icon: 'hash',
          keywords: [
            'iaid',
            'identity association',
            'interface identifier',
            'dhcpv6 iaid',
            'iaid calculator',
            'interface id',
            'rfc 8415',
          ],
        },
      ],
    },
    {
      title: 'Calculators & Planning',
      description: 'Network planning and optimization tools',
      items: [
        {
          href: makePath('/dhcp/calculators/lease-time'),
          label: 'Lease Time Calculator',
          description:
            'Calculate optimal DHCP lease times based on pool size, client count, and turnover rate with T1/T2 renewal timers',
          icon: 'clock',
          keywords: [
            'lease calculator',
            'lease time planning',
            't1 renewal',
            't2 rebinding',
            'pool optimization',
            'dhcp pool',
            'lease exhaustion',
            'ip churn',
          ],
        },
        {
          href: makePath('/dhcp/tools/fingerprinting'),
          label: 'Fingerprinting Database',
          description:
            'Identify devices by their DHCP fingerprints using Parameter Request List (Option 55) and Vendor Class patterns',
          icon: 'fingerprint',
          keywords: [
            'dhcp fingerprinting',
            'device identification',
            'option 55',
            'parameter request list',
            'vendor detection',
            'os detection',
            'device fingerprint',
            'client identification',
          ],
        },
      ],
    },
    {
      title: 'Configuration Generators',
      description: 'Server configuration generators and snippets',
      items: [
        {
          href: makePath('/dhcp/kea-isc-snippets'),
          label: 'Kea/ISC Config Snippets',
          description:
            'Generate complete subnet configurations for ISC dhcpd and Kea DHCP servers with pools, options, and reservations',
          icon: 'code-file',
          keywords: [
            'isc dhcpd',
            'kea dhcp',
            'config generator',
            'subnet configuration',
            'dhcpd.conf',
            'dhcp pools',
            'static reservations',
            'dhcp json',
          ],
        },
      ],
    },
  ],
  '/dns': [
    {
      href: makePath('/dns/generators'),
      title: 'DNS Generators',
      description: 'DNS record generators and zone file tools',
      items: [
        {
          href: makePath('/dns/generators/ptr-generator'),
          label: 'PTR Generator',
          description: 'Generate PTR records for reverse DNS zones',
          icon: 'ptr-generator',
          keywords: ['ptr records', 'reverse dns', 'in-addr.arpa', 'ip6.arpa'],
        },
      ],
    },
    {
      title: 'Reverse DNS',
      items: [
        {
          href: makePath('/dns/reverse/ptr-generator'),
          label: 'PTR Generator',
          description: 'Convert IPs/CIDRs to PTR names (in-addr.arpa / ip6.arpa) and example zone lines',
          icon: 'ptr-generator',
          keywords: ['ptr records', 'reverse dns', 'in-addr.arpa', 'ip6.arpa', 'zone file'],
        },
        {
          href: makePath('/dns/reverse/zone-generator'),
          label: 'Reverse Zone Generator',
          description: 'Generate full reverse zone files from CIDR + hostname template',
          icon: 'dns-reverse-zones-gen',
          keywords: ['reverse zone', 'zone file generator', 'ptr template', 'soa ns records'],
        },
        {
          href: makePath('/dns/reverse/reverse-zones'),
          label: 'Reverse Zones Calculator',
          description: 'Minimal set of reverse zones needed to delegate a CIDR (v4 & v6 nibble math)',
          icon: 'dns-reverse-zones-calc',
          keywords: ['reverse zones', 'zone delegation', 'nibble boundaries', 'octet boundaries'],
        },
        {
          href: makePath('/dns/reverse/ptr-sweep-planner'),
          label: 'PTR Sweep Planner',
          description: 'Plan PTR coverage for a block; list missing/extra PTRs against naming pattern',
          icon: 'dns-ptr-sweep',
          keywords: ['ptr sweep', 'coverage analysis', 'missing ptr', 'naming pattern'],
        },
      ],
    },
    {
      title: 'Record Generators',
      items: [
        {
          href: makePath('/dns/generators/a-aaaa-bulk'),
          label: 'A/AAAA Bulk Generator',
          description: 'Bulk create A and AAAA record sets from IP lists with TTL and RRset controls',
          icon: 'dns-a-records',
          keywords: ['a records', 'aaaa records', 'bulk generator', 'dns ttl', 'rrset'],
        },
        {
          href: makePath('/dns/generators/cname-builder'),
          label: 'CNAME Builder',
          description: 'Build valid CNAME records with loop detection and self-target checks',
          icon: 'dns-cname',
          keywords: ['cname records', 'canonical name', 'dns alias', 'loop detection'],
        },
        {
          href: makePath('/dns/generators/mx-planner'),
          label: 'MX Record Planner',
          description: 'Plan MX record priorities with fallback guidance and sample configurations',
          icon: 'dns-mx',
          keywords: ['mx records', 'mail exchange', 'email priority', 'mx fallback'],
        },
        {
          href: makePath('/dns/generators/srv-builder'),
          label: 'SRV Record Builder',
          description: 'Compose SRV records with service, protocol, priority, weight, port, and target validation',
          icon: 'dns-srv',
          keywords: ['srv records', 'service records', 'port priority', 'service discovery'],
        },
        {
          href: makePath('/dns/generators/txt-escape'),
          label: 'TXT Record Escape Tool',
          description: 'Safely escape and split TXT record strings into 255-character chunks with validation',
          icon: 'dns-txt',
          keywords: ['txt records', 'escape strings', '255 character limit', 'txt chunks'],
        },
        {
          href: makePath('/dns/generators/spf-builder'),
          label: 'SPF Policy Builder',
          description: 'Craft SPF policies with mechanism validation, qualifier control, and DNS lookup counting',
          icon: 'dns-spf',
          keywords: ['spf records', 'sender policy framework', 'email authentication', 'spf mechanisms'],
        },
        {
          href: makePath('/dns/generators/dkim-keygen'),
          label: 'DKIM Key Generator',
          description: 'Generate DKIM RSA keypairs (1024/2048-bit) with selectors and DNS TXT records',
          icon: 'dns-dkim',
          keywords: ['dkim', 'domain keys', 'email signing', 'rsa keypair', 'dkim selector'],
        },
        {
          href: makePath('/dns/generators/dmarc-builder'),
          label: 'DMARC Policy Builder',
          description: 'Create DMARC policies with alignment options, reporting addresses, and failure handling',
          icon: 'dns-dmarc',
          keywords: ['dmarc', 'email policy', 'quarantine reject', 'dmarc alignment', 'reporting'],
        },
        {
          href: makePath('/dns/generators/caa-builder'),
          label: 'CAA Record Builder',
          description: 'Build CAA records for certificate authority authorization with misconfiguration warnings',
          icon: 'dns-caa',
          keywords: ['caa records', 'certificate authority', 'ca authorization', 'ssl tls'],
        },
        {
          href: makePath('/dns/generators/tlsa-generator'),
          label: 'TLSA Generator',
          description:
            'Create TLSA (DANE) records from certificates or hashes with usage, selector, and matching type options',
          icon: 'dns-tlsa',
          keywords: ['tlsa records', 'dane', 'certificate pinning', 'tlsa hash', 'tls authentication'],
        },
        {
          href: makePath('/dns/generators/sshfp-generator'),
          label: 'SSHFP Generator',
          description:
            'Generate SSHFP records from SSH public keys or fingerprints with algorithm and fingerprint type selection',
          icon: 'dns-sshfp',
          keywords: ['dns', 'sshfp', 'ssh', 'public', 'key', 'fingerprint', 'algorithm', 'security'],
        },
        {
          href: makePath('/dns/generators/svcb-https-builder'),
          label: 'SVCB/HTTPS Builder',
          description:
            'Build SVCB and HTTPS resource records with service parameters like ALPN, port, and ECH configuration',
          icon: 'dns-svcb',
          keywords: ['dns', 'svcb', 'https', 'service', 'binding', 'alpn', 'port', 'ech', 'parameters'],
        },
        {
          href: makePath('/dns/generators/naptr-builder'),
          label: 'NAPTR Builder',
          description:
            'Construct NAPTR records for service discovery with order, preference, flags, service, regexp, and replacement fields',
          icon: 'dns-naptr',
          keywords: ['dns', 'naptr', 'service', 'discovery', 'order', 'preference', 'flags', 'regexp', 'replacement'],
        },
        {
          href: makePath('/dns/generators/loc-builder'),
          label: 'LOC Builder',
          description: 'Create LOC records from coordinates and convert between latitude/longitude and DNS LOC format',
          icon: 'dns-loc',
          keywords: ['dns', 'loc', 'location', 'coordinates', 'latitude', 'longitude', 'altitude', 'precision'],
        },
        {
          href: makePath('/dns/generators/rp-builder'),
          label: 'RP Builder',
          description: 'Generate RP (Responsible Person) records with mailbox and TXT domain name references',
          icon: 'dns-rp',
          keywords: ['dns', 'rp', 'responsible', 'person', 'mailbox', 'contact', 'txt', 'domain'],
        },
        {
          href: makePath('/dns/generators/idn-punycode'),
          label: 'IDN Punycode Converter',
          description: 'Convert Unicode domain names to Punycode and back with IDNA2008 normalization support',
          icon: 'dns-idn',
          keywords: ['dns', 'idn', 'punycode', 'unicode', 'domain', 'international', 'idna2008', 'normalization'],
        },
      ],
    },
    {
      title: 'DNS Utilities',
      items: [
        {
          href: makePath('/dns/record-validator'),
          label: 'DNS Record Validator',
          description:
            'Validate individual DNS resource record syntax (A/AAAA/CNAME/MX/TXT/SRV/CAA) with error detection',
          icon: 'dns-record-validator',
          keywords: [
            'dns',
            'record',
            'validator',
            'syntax',
            'A record',
            'AAAA',
            'CNAME',
            'MX',
            'TXT',
            'SRV',
            'CAA',
            'validation',
          ],
        },
        {
          href: makePath('/dns/ttl-calculator'),
          label: 'TTL Calculator',
          description: 'Humanize DNS TTL values and compute cache expiry times with recommendations',
          icon: 'dns-ttl',
          keywords: ['dns', 'ttl', 'time', 'live', 'cache', 'expiry', 'calculator', 'humanize', 'recommendations'],
        },
        {
          href: makePath('/dns/edns-size-estimator'),
          label: 'EDNS Size Estimator',
          description: 'Estimate DNS message size and UDP fragmentation risk with EDNS buffer recommendations',
          icon: 'dns-edns',
          keywords: ['dns', 'edns', 'message', 'size', 'udp', 'fragmentation', 'buffer', 'estimator', 'optimization'],
        },
        {
          href: makePath('/dns/label-normalizer'),
          label: 'DNS Label Normalizer',
          description: 'Normalize domain labels with homograph attack detection and script mixing warnings',
          icon: 'dns-label-normalize',
          keywords: [
            'dns',
            'label',
            'normalize',
            'domain',
            'homograph',
            'attack',
            'script',
            'mixing',
            'security',
            'idn',
          ],
        },
      ],
    },
    {
      title: 'Zone File Tools',
      items: [
        {
          href: makePath('/dns/zone/linter'),
          label: 'Zone Linter',
          description: 'Normalize and canonicalize BIND zone files with error checking and formatting',
          icon: 'dns-zone-linter',
          keywords: ['dns', 'zone', 'linter', 'normalize', 'canonicalize', 'bind', 'error', 'checking', 'format'],
        },
        {
          href: makePath('/dns/zone/diff'),
          label: 'Zone Diff',
          description: 'Compare two zone files and identify added, removed, and changed DNS records',
          icon: 'dns-zone-diff',
          keywords: ['dns', 'zone', 'diff', 'compare', 'changes', 'added', 'removed', 'modified', 'migration'],
        },
        {
          href: makePath('/dns/zone/stats'),
          label: 'Zone Statistics',
          description: 'Analyze zone file structure, record distribution, and configuration health',
          icon: 'dns-zone-stats',
          keywords: ['dns', 'zone', 'statistics', 'analysis', 'records', 'distribution', 'health', 'metrics'],
        },
        {
          href: makePath('/dns/zone/name-length-checker'),
          label: 'Name Length Checker',
          description: 'Validate DNS names against RFC length limits: 63 bytes per label, 255 bytes per FQDN',
          icon: 'dns-name-length',
          keywords: ['dns', 'name', 'length', 'validator', 'rfc', 'limits', 'label', 'fqdn', 'validation'],
        },
      ],
    },
    {
      title: 'DNSSEC Tools',
      items: [
        {
          href: makePath('/dns/dnssec/dnskey-tag'),
          label: 'DNSKEY Key Tag Calculator',
          description:
            'Compute the DNSKEY key tag from a DNSKEY RR (RFC 4034 algorithm) and display it alongside key meta',
          icon: 'dns-dnskey',
          keywords: ['dnssec', 'dnskey', 'key', 'tag', 'calculator', 'rfc', '4034', 'algorithm', 'ksk', 'zsk'],
        },
        {
          href: makePath('/dns/dnssec/ds-generator'),
          label: 'DS Record Generator',
          description:
            'Generate DS records (SHA-1/256/384) from a DNSKEY or public key, with copyable output for parent submission',
          icon: 'dns-ds',
          keywords: ['dnssec', 'ds', 'delegation', 'signer', 'sha1', 'sha256', 'sha384', 'parent', 'zone', 'trust'],
        },
        {
          href: makePath('/dns/dnssec/nsec3-hash'),
          label: 'NSEC3 Hash Calculator',
          description:
            'Calculate NSEC3 owner hashes for a name given salt, iterations, and algorithm, showing the hashed owner FQDN',
          icon: 'dns-nsec3',
          keywords: ['dnssec', 'nsec3', 'hash', 'calculator', 'salt', 'iterations', 'algorithm', 'sha1', 'privacy'],
        },
        {
          href: makePath('/dns/dnssec/cds-cdnskey-builder'),
          label: 'CDS/CDNSKEY Builder',
          description: 'Build CDS/CDNSKEY RRs from child DNSKEYs to enable automated DS updates at the parent',
          icon: 'dns-cds',
          keywords: [
            'dnssec',
            'cds',
            'cdnskey',
            'builder',
            'automated',
            'ds',
            'updates',
            'parent',
            'child',
            'delegation',
          ],
        },
        {
          href: makePath('/dns/dnssec/rrsig-planner'),
          label: 'RRSIG Planner',
          description:
            'Suggest RRSIG validity windows (inception/expiration) based on TTLs and desired overlap, with renewal lead-time guidance',
          icon: 'dns-rrsig',
          keywords: [
            'dnssec',
            'rrsig',
            'planner',
            'validity',
            'windows',
            'inception',
            'expiration',
            'ttl',
            'overlap',
            'renewal',
          ],
        },
      ],
    },
  ],
  '/diagnostics': [
    {
      title: 'DNS Diagnostics',
      items: [
        {
          href: makePath('/diagnostics/dns/lookup'),
          label: 'DNS Lookup',
          description:
            'Resolve DNS records (A, AAAA, CNAME, MX, TXT, NS, SOA, CAA) using various public resolvers or custom DNS servers',
          icon: 'dns-lookup',
          keywords: ['dns lookup', 'query records', 'resolve domain', 'dns query', 'public resolvers'],
        },
        {
          href: makePath('/diagnostics/dns/reverse-lookup'),
          label: 'Reverse DNS Lookup',
          description:
            'Perform reverse DNS lookups (PTR records) for IPv4 and IPv6 addresses with automatic zone formatting',
          icon: 'dns-reverse',
          keywords: ['reverse lookup', 'ptr query', 'ip to hostname', 'in-addr.arpa', 'ip6.arpa'],
        },
        {
          href: makePath('/diagnostics/dns/propagation'),
          label: 'DNS Propagation Checker',
          description:
            'Check DNS record propagation across multiple public resolvers (Cloudflare, Google, Quad9, OpenDNS)',
          icon: 'dns-propagation',
          keywords: ['dns propagation', 'global check', 'resolver consistency', 'dns sync'],
        },
        {
          href: makePath('/diagnostics/dns/spf-evaluator'),
          label: 'SPF Record Evaluator',
          description:
            'Analyze SPF records with recursive expansion of includes/redirects and DNS lookup limit tracking',
          icon: 'dns-spf-eval',
          keywords: ['spf', 'evaluator', 'recursive', 'includes', 'redirects', 'dns', 'lookups', 'sender', 'policy'],
        },
        {
          href: makePath('/diagnostics/dns/dmarc-check'),
          label: 'DMARC Policy Checker',
          description: 'Analyze DMARC policies, check alignment settings, and identify configuration issues',
          icon: 'dns-dmarc-check',
          keywords: ['dmarc', 'policy', 'check', 'alignment', 'quarantine', 'reject', 'rua', 'ruf', 'analysis'],
        },
        {
          href: makePath('/diagnostics/dns/caa-effective'),
          label: 'CAA Effective Policy',
          description: 'Walk domain label chain to find effective CAA policies for certificate authority authorization',
          icon: 'dns-caa-check',
          keywords: [
            'caa',
            'effective',
            'policy',
            'certificate',
            'authority',
            'authorization',
            'chain',
            'domain',
            'ssl',
          ],
        },
        {
          href: makePath('/diagnostics/dns/ns-soa-check'),
          label: 'NS/SOA Consistency Check',
          description: 'Verify nameserver resolution and analyze SOA record parameters for DNS configuration health',
          icon: 'dns-ns-soa',
          keywords: ['ns', 'soa', 'nameserver', 'consistency', 'check', 'resolution', 'parameters', 'health', 'serial'],
        },
        {
          href: makePath('/diagnostics/dns/dnssec-adflag'),
          label: 'DNSSEC AD Flag Checker',
          description:
            'Query DNS records via DoH and report if the AD (Authenticated Data) bit is set for DNSSEC validation',
          icon: 'dns-adflag',
          keywords: ['dnssec', 'ad', 'flag', 'authenticated', 'data', 'doh', 'validation', 'security', 'dns'],
        },
        {
          href: makePath('/diagnostics/dns/dnssec-validation-chain'),
          label: 'DNSSEC Validation Chain',
          description: 'Validate full DNSSEC chain from root to domain with DS/DNSKEY matching and RRSIG verification',
          icon: 'dnssec-chain',
          keywords: [
            'dnssec',
            'validation',
            'chain',
            'ds',
            'dnskey',
            'rrsig',
            'trust',
            'security',
            'dns',
            'root',
            'authenticated',
          ],
        },
        {
          href: makePath('/diagnostics/dns/blacklist-checker'),
          label: 'DNS Blacklist Checker',
          description: 'Check if IP or domain is listed on spam blacklists for email deliverability troubleshooting',
          icon: 'blacklist',
          keywords: [
            'dnsbl',
            'rbl',
            'blacklist',
            'spam',
            'spamhaus',
            'sorbs',
            'email',
            'deliverability',
            'reputation',
            'blocklist',
            'listing',
            'delisting',
          ],
        },
        {
          href: makePath('/diagnostics/dns/axfr-tester'),
          label: 'AXFR Security Tester',
          description: 'Test if DNS zone transfers are improperly exposed - detect critical security vulnerabilities',
          icon: 'zone-transfer-safe',
          keywords: [
            'axfr',
            'zone',
            'transfer',
            'security',
            'vulnerability',
            'dns',
            'leak',
            'audit',
            'test',
            'nameserver',
          ],
        },
        {
          href: makePath('/diagnostics/dns/query-performance'),
          label: 'DNS Query Performance',
          description: 'Compare DNS resolver speeds across multiple providers to find the fastest for your location',
          icon: 'zap',
          featured: true,
          keywords: [
            'dns',
            'performance',
            'speed',
            'test',
            'resolver',
            'comparison',
            'latency',
            'cloudflare',
            'google',
            'quad9',
            'opendns',
            'response',
            'time',
            'fastest',
            'benchmark',
          ],
        },
        {
          href: makePath('/diagnostics/dns/soa-serial'),
          label: 'SOA Serial Analyzer',
          description:
            'Analyze Start of Authority records to interpret serial number formats and examine DNS zone timing parameters',
          icon: 'dns-soa',
          keywords: [
            'soa',
            'serial',
            'analyzer',
            'zone',
            'timing',
            'parameters',
            'yyyymmddnn',
            'unix',
            'timestamp',
            'dns',
          ],
        },
        {
          href: makePath('/diagnostics/dns/trace'),
          label: 'DNS Trace',
          description:
            'Iterative trace from root to authoritative nameservers via DNS over HTTPS with path and timing details',
          icon: 'dns-trace',
          keywords: ['dns', 'trace', 'root', 'authoritative', 'nameservers', 'doh', 'path', 'timing', 'iterative'],
        },
        {
          href: makePath('/diagnostics/dns/glue-check'),
          label: 'Glue Check',
          description: 'Check which NS names require glue records and whether A/AAAA glue records exist for the zone',
          icon: 'dns-glue',
          keywords: ['dns', 'glue', 'records', 'nameservers', 'ns', 'a-records', 'aaaa', 'zone', 'delegation', 'check'],
        },
        {
          href: makePath('/diagnostics/dns/spf-flatten'),
          label: 'SPF Flatten',
          description: 'Resolve include:/redirect= mechanisms and output a flattened SPF record with DNS lookup counts',
          icon: 'spf-flatten',
          keywords: [
            'spf',
            'flatten',
            'include',
            'redirect',
            'dns',
            'lookups',
            'optimization',
            'email',
            'authentication',
          ],
        },
      ],
    },
    {
      title: 'HTTP Diagnostics',
      items: [
        {
          href: makePath('/diagnostics/http/headers'),
          label: 'HTTP Headers Analyzer',
          description: 'Analyze HTTP headers and response metadata with custom method and header support',
          icon: 'http-headers',
          keywords: ['http', 'headers', 'analyzer', 'response', 'metadata', 'custom', 'method', 'request'],
        },
        {
          href: makePath('/diagnostics/http/redirect-trace'),
          label: 'Redirect Trace',
          description: 'Follow HTTP redirects and trace the full chain with security upgrade detection',
          icon: 'redirect-trace',
          keywords: ['http', 'redirect', 'trace', 'chain', 'hsts', 'security', 'upgrade', 'follow'],
        },
        {
          href: makePath('/diagnostics/http/security'),
          label: 'Security Headers Analyzer',
          description: 'Analyze security headers (HSTS, CSP, X-Frame-Options) with grading and recommendations',
          icon: 'security-headers',
          keywords: ['http', 'security', 'headers', 'hsts', 'csp', 'x-frame-options', 'analyzer', 'grade'],
        },
        {
          href: makePath('/diagnostics/http/cors-check'),
          label: 'CORS Policy Checker',
          description: 'Test CORS policies with preflight requests and origin validation',
          icon: 'cors-check',
          keywords: ['cors', 'policy', 'check', 'preflight', 'origin', 'validation', 'cross-origin', 'options'],
        },
        {
          href: makePath('/diagnostics/http/perf'),
          label: 'HTTP Performance Analyzer',
          description: 'Measure HTTP performance timing including DNS, TCP, TLS, and TTFB metrics',
          icon: 'http-perf',
          keywords: ['http', 'performance', 'timing', 'dns', 'tcp', 'tls', 'ttfb', 'metrics', 'analyzer'],
        },
        {
          href: makePath('/diagnostics/http/compression'),
          label: 'HTTP Compression Check',
          description: 'Test gzip, brotli, and deflate compression support and measure size differences',
          icon: 'archive',
          keywords: ['http', 'compression', 'gzip', 'brotli', 'deflate', 'size', 'reduction', 'performance'],
        },
        {
          href: makePath('/diagnostics/http/cookie-security'),
          label: 'Cookie Security Inspector',
          description: 'Inspect Set-Cookie headers for Secure, HttpOnly, SameSite, and other security attributes',
          icon: 'cookie',
          keywords: ['http', 'cookie', 'security', 'secure', 'httponly', 'samesite', 'csrf', 'xss', 'attributes'],
        },
      ],
    },
    {
      title: 'TLS Diagnostics',
      items: [
        {
          href: makePath('/diagnostics/tls/certificate'),
          label: 'TLS Certificate Analyzer',
          description:
            'Analyze TLS certificates, view certificate chains, check expiration dates, and examine Subject Alternative Names',
          icon: 'tls-cert',
          keywords: ['tls', 'certificate', 'analyzer', 'chain', 'expiry', 'san', 'ssl', 'x509', 'fingerprint'],
        },
        {
          href: makePath('/diagnostics/tls/versions'),
          label: 'TLS Versions Probe',
          description: 'Test which TLS protocol versions a server supports and assess overall security posture',
          icon: 'tls-version',
          keywords: ['tls', 'versions', 'probe', 'security', 'protocol', 'support', 'deprecated', 'assessment'],
        },
        {
          href: makePath('/diagnostics/tls/alpn'),
          label: 'TLS ALPN Negotiation',
          description:
            'Test Application-Layer Protocol Negotiation to see which protocol a server selects (HTTP/2, HTTP/3)',
          icon: 'tls-alpn',
          keywords: ['tls', 'alpn', 'negotiation', 'http2', 'http3', 'protocol', 'handshake', 'application'],
        },
        {
          href: makePath('/diagnostics/tls/ocsp-stapling'),
          label: 'OCSP Stapling',
          description: 'Report if server staples OCSP responses and display basic certificate status information',
          icon: 'ocsp-stapling',
          keywords: ['tls', 'ocsp', 'stapling', 'certificate', 'status', 'revocation', 'ssl', 'handshake', 'response'],
        },
        {
          href: makePath('/diagnostics/tls/cipher-presets'),
          label: 'Cipher Presets',
          description:
            'Probe connectivity with preset cipher lists (modern/intermediate/legacy) and assess security level',
          icon: 'tls-cipher-presets',
          keywords: ['tls', 'cipher', 'presets', 'modern', 'intermediate', 'legacy', 'security', 'suites', 'probe'],
        },
        {
          href: makePath('/diagnostics/tls/banner'),
          label: 'Service Banner Grabber',
          description: 'Retrieve service banners from SSH, SMTP, HTTP, FTP, and other network services',
          icon: 'terminal',
          keywords: ['banner', 'service', 'ssh', 'smtp', 'ftp', 'http', 'telnet', 'fingerprinting', 'reconnaissance'],
        },
        {
          href: makePath('/diagnostics/tls/handshake-analyzer'),
          label: 'TLS Handshake Analyzer',
          description:
            'Analyze TLS/SSL handshake timing breakdown with detailed phase information and certificate exchange',
          icon: 'handshake',
          featured: true,
          keywords: [
            'tls',
            'handshake',
            'analyzer',
            'timing',
            'performance',
            'latency',
            'ssl',
            'certificate',
            'cipher',
            'negotiation',
          ],
        },
        {
          href: makePath('/diagnostics/tls/ct-log-search'),
          label: 'CT Log Search',
          description: 'Search Certificate Transparency logs to discover all certificates issued for a domain',
          icon: 'badge',
          featured: true,
          keywords: [
            'ct',
            'certificate',
            'transparency',
            'log',
            'search',
            'crt.sh',
            'ssl',
            'tls',
            'san',
            'subdomains',
            'discovery',
            'issuer',
            'validity',
            'wildcard',
            'monitoring',
          ],
        },
      ],
    },
    {
      title: 'Network Diagnostics',
      items: [
        {
          href: makePath('/diagnostics/network/tcp-port-check'),
          label: 'TCP Port Checker',
          description: 'Test TCP connectivity to host:port combinations and measure connection latency',
          icon: 'network-port',
          keywords: ['tcp', 'port', 'check', 'connectivity', 'latency', 'open', 'closed', 'firewall', 'scan'],
        },
        {
          href: makePath('/diagnostics/network/http-ping'),
          label: 'HTTP Ping',
          description: 'Measure HTTP/HTTPS response latency with statistical analysis (median, p95) without raw ICMP',
          icon: 'network-ping',
          keywords: ['http', 'ping', 'latency', 'response', 'time', 'statistics', 'median', 'p95', 'web', 'api'],
        },
        {
          href: makePath('/diagnostics/network/bgp-route-lookup'),
          label: 'BGP Route Lookup',
          description:
            'Look up BGP routing information for IP addresses and prefixes, view AS paths, origin AS, and peering data',
          icon: 'signpost',
          keywords: [
            'bgp',
            'routing',
            'as',
            'asn',
            'autonomous system',
            'prefix',
            'peer',
            'origin',
            'path',
            'ripe',
            'ris',
            'route',
            'internet routing',
          ],
        },
        {
          href: makePath('/diagnostics/network/ipv6-connectivity-checker'),
          label: 'IPv6 Connectivity Checker',
          description: 'Test IPv6 and IPv4 connectivity to determine dual-stack capability and protocol preference',
          icon: 'ipv6-check',
          keywords: [
            'ipv6',
            'ipv4',
            'connectivity',
            'dual-stack',
            'protocol',
            'test',
            'network',
            'internet',
            'address',
          ],
        },
        {
          href: makePath('/diagnostics/network/asn-geo-lookup'),
          label: 'ASN & Geolocation Lookup',
          description: 'Look up IP address geolocation, ISP, and autonomous system information',
          icon: 'map',
          keywords: [
            'asn',
            'geolocation',
            'ip',
            'lookup',
            'location',
            'isp',
            'organization',
            'country',
            'city',
            'coordinates',
            'autonomous system',
            'network',
            'provider',
          ],
        },
      ],
    },
    {
      title: 'Email Diagnostics',
      items: [
        {
          href: makePath('/diagnostics/email/mx-health'),
          label: 'MX Health Checker',
          description: 'Check mail server (MX) health including DNS resolution and SMTP port connectivity testing',
          icon: 'email-mx',
          keywords: ['mx', 'health', 'check', 'mail', 'server', 'smtp', 'port', 'connectivity', 'dns', 'email'],
        },
        {
          href: makePath('/diagnostics/email/spf-check'),
          label: 'SPF Policy Checker',
          description: 'Analyze SPF records with email deliverability focus and authentication policy evaluation',
          icon: 'mail-check',
          keywords: ['spf', 'policy', 'check', 'email', 'deliverability', 'authentication', 'sender', 'authorization'],
        },
        {
          href: makePath('/diagnostics/email/dmarc-check'),
          label: 'DMARC Policy Checker',
          description:
            'Check DMARC policies with email deliverability impact analysis and configuration recommendations',
          icon: 'email-dmarc',
          keywords: ['dmarc', 'policy', 'check', 'email', 'deliverability', 'authentication', 'reporting', 'alignment'],
        },
        {
          href: makePath('/diagnostics/email/mail-tls-check'),
          label: 'SMTP TLS Checker',
          description: 'Check if mail server supports TLS/STARTTLS encryption and validate certificate security',
          icon: 'mailbox',
          keywords: [
            'smtp',
            'tls',
            'starttls',
            'ssl',
            'encryption',
            'certificate',
            'mail',
            'server',
            'security',
            'email',
          ],
        },
        {
          href: makePath('/diagnostics/email/greylist-tester'),
          label: 'Greylisting Tester',
          description: 'Test if mail server implements greylisting by analyzing multiple connection attempts',
          icon: 'mustache',
          keywords: [
            'greylist',
            'greylisting',
            'smtp',
            'mail',
            'server',
            'spam',
            'filter',
            'anti-spam',
            'email',
            'delay',
          ],
        },
      ],
    },
    {
      title: 'RDAP Diagnostics',
      items: [
        {
          href: makePath('/diagnostics/rdap/domain'),
          label: 'Domain RDAP Lookup',
          description:
            'Query domain registration data using RDAP through IANA bootstrap registry with structured JSON responses',
          icon: 'dns-lookup',
          keywords: ['rdap', 'domain', 'registration', 'whois', 'iana', 'bootstrap', 'registry', 'json', 'lookup'],
        },
        {
          href: makePath('/diagnostics/rdap/ip'),
          label: 'IP Address RDAP Lookup',
          description:
            'Look up IP address allocation and registration data using RDAP through Regional Internet Registries',
          icon: 'rdap-ip',
          keywords: ['rdap', 'ip', 'allocation', 'registration', 'rir', 'arin', 'ripe', 'apnic', 'lacnic', 'afrinic'],
        },
        {
          href: makePath('/diagnostics/rdap/asn'),
          label: 'ASN RDAP Lookup',
          description:
            'Query Autonomous System Number allocation and registration data using RDAP through RIR services',
          icon: 'rdap-asn',
          keywords: ['rdap', 'asn', 'autonomous', 'system', 'number', 'allocation', 'registry', 'bgp', 'routing'],
        },
      ],
    },
  ],
  '/reference': [
    {
      title: 'Fundamentals',
      items: [
        {
          href: makePath('/reference/cidr'),
          label: 'CIDR Notation Explained',
          description: 'What CIDR is, why it replaced IP classes, and how to read network prefixes',
          icon: 'ref-cidr',
          keywords: ['cidr explained', 'classless routing', 'slash notation', 'ip classes', 'prefix length'],
        },
        {
          href: makePath('/reference/vlsm'),
          label: 'VLSM in Plain English',
          description: 'Variable Length Subnet Masking - when to use it and common pitfalls',
          icon: 'ref-vlsm',
          keywords: [
            'vlsm explained',
            'variable length subnet',
            'subnet planning',
            'network design',
            'common pitfalls',
          ],
        },
        {
          href: makePath('/reference/supernetting'),
          label: 'Route Summarization / Supernetting',
          description: 'Combine multiple networks into single routes for efficient routing',
          icon: 'ref-supernetting',
          keywords: ['route summarization', 'supernetting', 'prefix aggregation', 'bgp ospf', 'routing optimization'],
        },
      ],
    },
    {
      title: 'IPv6 Addressing',
      items: [
        {
          href: makePath('/reference/ipv6-address-types'),
          label: 'IPv6 Address Types & Key Prefixes',
          description: 'Global unicast, ULA, link-local, multicast, and special IPv6 addresses',
          icon: 'ref-ipv6-address-types',
          keywords: [
            'ipv6 address types',
            'global unicast',
            'ula fd00',
            'link-local fe80',
            'multicast ff00',
            'special prefixes',
          ],
        },
        {
          href: makePath('/reference/ipv6-prefix-lengths'),
          label: 'Common IPv6 Prefix Lengths',
          description: 'Quick reference for /128, /127, /64, /60, /56, /48, /32 with typical uses',
          icon: 'ref-ipv6-prefix-lens',
          keywords: ['ipv6 prefix lengths', '/128 /64 /48', 'subnet sizes', 'allocation hierarchy'],
        },
        {
          href: makePath('/reference/ipv6-embedded-ipv4'),
          label: 'IPv4 in IPv6',
          description: 'IPv4-mapped addresses, 6to4, Teredo, and transition mechanisms',
          icon: 'ref-ipv4-in-ipv6',
          keywords: ['ipv4-mapped ipv6', '6to4', 'teredo', 'transition mechanisms', 'dual-stack', '::ffff'],
        },
        {
          href: makePath('/reference/ipv6-privacy-addresses'),
          label: 'IPv6 Privacy Addresses',
          description: 'SLAAC privacy extensions: temporary vs stable interface identifiers',
          icon: 'ref-ipv6-privacy-address',
          keywords: ['ipv6 privacy', 'slaac extensions', 'temporary addresses', 'rfc 4941', 'interface identifiers'],
        },
      ],
    },
    {
      title: 'Special Addresses',
      items: [
        {
          href: makePath('/reference/common-subnets'),
          label: 'Common Subnet Sizes',
          description: 'Quick reference for common subnet sizes and host counts',
          icon: 'ref-common-subnets',
          keywords: ['subnet sizes', 'host counts', '/24 /25 /26', 'quick reference'],
        },
        {
          href: makePath('/reference/network-classes'),
          label: 'Network Classes (A/B/C)',
          description: 'Legacy network classes and their modern CIDR equivalents',
          icon: 'ref-network-classes',
          keywords: ['network classes', 'class a b c', 'legacy classful', 'cidr equivalents'],
        },
        {
          href: makePath('/reference/reserved-ranges'),
          label: 'Reserved IP Ranges',
          description: 'Comprehensive list of reserved and special-use IP address ranges',
          icon: 'ref-reserved-ranges',
          keywords: ['reserved ip ranges', 'special-use addresses', 'rfc allocations'],
        },
        {
          href: makePath('/reference/special-use-ipv4'),
          label: 'Special-Use IPv4 Blocks (RFC 6890)',
          description: 'Reserved IPv4 ranges including private networks, CGNAT, and test blocks',
          icon: 'ref-special-blocks',
          keywords: ['rfc 6890', 'special-use ipv4', 'private networks', '10.0.0.0 192.168.0.0', 'cgnat test blocks'],
        },
        {
          href: makePath('/reference/private-vs-public-ip'),
          label: 'Private vs Public IP Addresses',
          description: 'Understanding private/public IPs, NAT implications, and identification',
          icon: 'ref-public-vs-private',
          keywords: ['private vs public ip', 'rfc 1918', 'nat routable', 'ip identification'],
        },
        {
          href: makePath('/reference/cgnat'),
          label: 'Carrier-Grade NAT Explained',
          description: 'CGNAT (100.64.0.0/10), how to identify it, and service impacts',
          icon: 'ref-carrier-nat',
          keywords: ['cgnat explained', '100.64.0.0/10', 'rfc 6598', 'shared address space', 'isp carrier nat'],
        },
        {
          href: makePath('/reference/link-local-apipa'),
          label: 'Link-Local & APIPA Addresses',
          description: 'IPv4 APIPA (169.254/16) and IPv6 link-local (fe80::/10) at a glance',
          icon: 'ref-link-local-apia',
          keywords: ['link-local', 'apipa 169.254', 'fe80::', 'zero-conf', 'self-assigned'],
        },
        {
          href: makePath('/reference/multicast'),
          label: 'IPv4 & IPv6 Multicast Basics',
          description: 'Multicast scopes, well-known groups, and local subnet limitations',
          icon: 'ref-multicast-basics',
          keywords: ['multicast basics', '224.0.0.0 ff00::', 'igmp mld', 'multicast scopes', 'group communication'],
        },
      ],
    },
    {
      title: 'DNS & Protocols',
      items: [
        {
          href: makePath('/reference/reverse-dns'),
          label: 'Reverse DNS (PTR Records)',
          description: 'How in-addr.arpa and ip6.arpa work with examples for IPv4 and IPv6',
          icon: 'ref-reverse-dns',
          keywords: ['reverse dns explained', 'ptr records', 'in-addr.arpa', 'ip6.arpa', 'hostname lookup'],
        },
        {
          href: makePath('/reference/reverse-zones'),
          label: 'Reverse Zones for CIDR Delegation',
          description: 'Minimal reverse DNS zones needed to delegate IPv4 and IPv6 CIDR blocks',
          icon: 'ref-reverse-zones',
          keywords: ['reverse zones', 'cidr delegation', 'nibble octet boundaries', 'zone authority'],
        },
        {
          href: makePath('/reference/icmp'),
          label: 'ICMP & ICMPv6: Common Types',
          description: 'Practical guide to ICMP message types for network troubleshooting',
          icon: 'ref-icmp',
          keywords: [
            'icmp message types',
            'ping traceroute',
            'destination unreachable',
            'time exceeded',
            'troubleshooting',
          ],
        },
        {
          href: makePath('/reference/arp-vs-ndp'),
          label: 'ARP vs NDP',
          description: 'Side-by-side comparison of IPv4 ARP and IPv6 Neighbor Discovery',
          icon: 'ref-arp-vs-ndp',
          keywords: ['arp vs ndp', 'neighbor discovery', 'address resolution', 'layer2 protocol', 'mac solicitation'],
        },
      ],
    },
    {
      title: 'Network Operations',
      items: [
        {
          href: makePath('/reference/asn'),
          label: 'What is an ASN?',
          description: 'Autonomous Systems, BGP basics, and how IP addresses map to ASNs',
          icon: 'ref-asn',
          keywords: ['asn explained', 'autonomous system', 'bgp routing', 'iana rir allocation', 'asn lookup'],
        },
        {
          href: makePath('/reference/ports'),
          label: 'Common TCP/UDP Ports',
          description: 'Quick reference for frequently used port numbers and services',
          icon: 'ref-ports',
          keywords: ['tcp udp ports', 'well-known ports', 'port numbers', 'services reference', 'firewall rules'],
        },
        {
          href: makePath('/reference/wildcard-masks'),
          label: 'ACL Wildcard Masks',
          description: 'Wildcard masks vs netmasks, quick conversions and ACL examples',
          icon: 'ref-wildcard-masks',
          keywords: ['wildcard masks', 'acl rules', 'inverse mask', 'cisco juniper', 'firewall acl'],
        },
        {
          href: makePath('/reference/mtu-mss'),
          label: 'Common MTU/MSS Values',
          description: 'MTU and MSS values for Ethernet, PPPoE, VPN, and overhead calculations',
          icon: 'ref-mtu-mss',
          keywords: ['mtu mss values', 'ethernet pppoe', 'vpn overhead', 'fragmentation', 'jumbo frames'],
        },
      ],
    },
  ],
};

export const aboutPages: NavItem[] = [
  {
    href: makePath('/about/api'),
    label: 'API Usage',
    icon: 'cli',
    description: 'Using our free public REST API for network calculations and IP tools',
    keywords: ['api', 'networking', 'ipv4', 'ipv6', 'network', 'tools', 'dns', 'cidr', 'subnet'],
  },
  {
    href: makePath('/about/attributions'),
    label: 'Attributions',
    icon: 'clap',
    description: 'Shout outs to sponsors, contributors and other authors who made Networking Toolbox possible',
    keywords: ['attributions', 'credits', 'thanks', 'sponsors', 'contributors', 'libraries'],
  },
  {
    href: makePath('/about/author'),
    label: 'Author',
    icon: 'dead-bot',
    description: 'About Alicia Sykes, and how and why she built Networking Toolbox',
    keywords: ['author', 'about', 'bio', 'Alicia Sykes', 'github'],
  },
  {
    href: makePath('/about/building'),
    label: 'Building',
    icon: 'hammer',
    description: 'Build Networking Toolbox from source, self-host, edit, or contribute to the project',
    keywords: ['building', 'sveltekit', 'github', 'npm', 'svelte', 'typescript', 'developing documentation'],
  },
  {
    href: makePath('/about/support'),
    label: 'Support',
    icon: 'headset',
    description: 'Get support, dedicated hosting, enterprise SSO, SLA or custom feature/tool development',
    keywords: ['support', 'enterprise', 'sso', 'sla', 'custom', 'development', 'hosting', 'contact'],
  },
  {
    href: makePath('/about/legal/license'),
    label: 'MIT License',
    description: `Networking Toolbox's MIT license, summary, and what it means for you`,
    keywords: ['license', 'mit', 'opensource', 'permissions', 'limitations', 'conditions'],
  },
  {
    href: makePath('/about/legal/security'),
    label: 'Security Policy',
    description: 'Report security vulnerabilities and learn about our security practices',
    keywords: ['security', 'policy', 'vulnerability', 'disclosure', 'reporting', 'bug', 'bounty'],
  },
  {
    href: makePath('/about/legal/accessibility'),
    label: 'Accessibility Policy',
    description: 'WCAG AA compliant with keyboard navigation, screen reader support, and customizable display options',
    keywords: ['accessibility', 'wcag', 'a11y', 'keyboard', 'screen reader', 'contrast', 'dyslexic', 'aria'],
  },
  {
    href: makePath('/about/legal/community'),
    label: 'Community Guidelines',
    description: 'Code of conduct and community standards for contributors',
    keywords: ['community', 'guidelines', 'code', 'conduct', 'contributor', 'covenant', 'behavior', 'standards'],
  },
  {
    href: makePath('/about/legal/cookies'),
    label: 'Cookie Policy',
    description: "Our cookie policy: we don't use them",
    keywords: ['cookie', 'cookies', 'policy', 'tracking', 'localstorage', 'privacy'],
  },
  {
    href: makePath('/about/self-hosting'),
    label: 'Self-Hosting',
    icon: 'docker',
    description: 'Guide to self-hosting Networking Toolbox on your own server or infrastructure',
    keywords: ['self-hosting', 'deployment', 'docker', 'portainer', 'vercel', 'node', 'nginx'],
  },
];

export const legalPages: NavItem[] = [
  {
    href: makePath('/about/legal/license'),
    label: 'MIT License',
    description: 'View the MIT license terms and conditions',
    icon: 'certificate',
  },
  {
    href: makePath('/about/legal/privacy'),
    label: 'Privacy Policy',
    description: 'Learn how we handle your data and protect your privacy',
    icon: 'hide',
  },
  {
    href: makePath('/about/legal/security'),
    label: 'Security Policy',
    description: 'Report vulnerabilities and learn about our security practices',
    icon: 'shield',
  },
  {
    href: makePath('/about/legal/accessibility'),
    label: 'Accessibility Policy',
    description: 'Learn about our accessibility features and WCAG AA compliance',
    icon: 'accessibility',
  },
  {
    href: makePath('/about/legal/community'),
    label: 'Community Guidelines',
    description: 'Code of conduct and community standards for contributors',
    icon: 'users',
  },
  {
    href: makePath('/about/legal/cookies'),
    label: 'Cookie Policy',
    description: "Our cookie policy: we don't use them",
    icon: 'cookie',
  },
];

export const footerLinks: NavItem[] = [
  { href: makePath('/about'), label: 'About' },
  { href: site.repo, label: 'GitHub' },
  { href: author.sponsor, label: 'Sponsor' },
  { href: author.portfolio, label: 'More Apps →' },
];

// All pages for homepage navigation - combines standalone pages with sub-pages
export const ALL_PAGES: NavItem[] = [
  ...Object.values(SUB_NAV)
    .map((section) => extractAllNavItems(section as (NavItem | NavGroup)[]))
    .flat(),
];
