<script lang="ts">
  import { tooltip } from '$lib/actions/tooltip.js';
  import Icon from '$lib/components/global/Icon.svelte';
  import { useClipboard } from '$lib/composables';
  import { generatePTRName, generateCIDRPTRs, type PTRRecord } from '$lib/utils/reverse-dns.js';

  let inputValue = $state('192.168.1.100');
  let inputType = $state<'single' | 'cidr'>('single');
  let results = $state<{
    success: boolean;
    error?: string;
    entries: PTRRecord[];
    summary: {
      totalEntries: number;
      ipv4Entries: number;
      ipv6Entries: number;
      uniqueZones: number;
    };
  } | null>(null);
  const clipboard = useClipboard();
  let selectedExample = $state<string | null>(null);
  let _userModified = $state(false);

  const examples = [
    {
      label: 'Single IPv4',
      input: '192.168.1.100',
      type: 'single' as const,
      description: 'Generate PTR for single IPv4 address',
    },
    {
      label: 'Single IPv6',
      input: '2001:db8::1',
      type: 'single' as const,
      description: 'Generate PTR for single IPv6 address',
    },
    {
      label: 'IPv4 /28 Block',
      input: '192.168.1.16/28',
      type: 'cidr' as const,
      description: 'Generate PTRs for /28 subnet (16 addresses)',
    },
    {
      label: 'IPv4 /24 Network',
      input: '10.0.0.0/24',
      type: 'cidr' as const,
      description: 'Generate PTRs for entire /24 network',
    },
    {
      label: 'IPv6 /64 Network',
      input: '2001:db8:1000::/64',
      type: 'cidr' as const,
      description: 'Generate IPv6 PTR examples for /64',
    },
  ];

  function loadExample(example: (typeof examples)[0]) {
    inputValue = example.input;
    inputType = example.type;
    selectedExample = example.label;
    _userModified = false;
    generatePTRs();
  }

  function generatePTRs() {
    if (!inputValue.trim()) {
      results = null;
      return;
    }

    try {
      const trimmed = inputValue.trim();
      let entries: PTRRecord[] = [];

      if (inputType === 'single') {
        // Single IP address
        const record = generatePTRName(trimmed);
        if (record) {
          entries.push(record);
        } else {
          throw new Error('Invalid IP address format');
        }
      } else {
        // CIDR notation
        entries = generateCIDRPTRs(trimmed, 1000);
      }

      // Generate summary
      const summary = {
        totalEntries: entries.length,
        ipv4Entries: entries.filter((e) => e.type === 'IPv4').length,
        ipv6Entries: entries.filter((e) => e.type === 'IPv6').length,
        uniqueZones: [...new Set(entries.map((e) => e.zone))].length,
      };

      results = {
        success: true,
        entries,
        summary,
      };
    } catch (error) {
      results = {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        entries: [],
        summary: { totalEntries: 0, ipv4Entries: 0, ipv6Entries: 0, uniqueZones: 0 },
      };
    }
  }

  function handleInputChange() {
    _userModified = true;
    selectedExample = null;
    generatePTRs();
  }

  function handleTypeChange() {
    _userModified = true;
    selectedExample = null;
    generatePTRs();
  }

  // Generate on component load
  generatePTRs();
</script>

<div class="card">
  <header class="card-header">
    <h1>Reverse PTR Generator</h1>
    <p>Convert IP addresses and CIDR blocks to PTR record names and zone file examples</p>
  </header>

  <!-- Educational Overview Card -->
  <div class="card info-card">
    <div class="overview-content">
      <div class="overview-item">
        <Icon name="rotate" size="sm" />
        <div>
          <strong>Reverse DNS:</strong> PTR records map IP addresses back to hostnames using <code>in-addr.arpa</code>
          (IPv4) and <code>ip6.arpa</code> (IPv6) zones.
        </div>
      </div>
      <div class="overview-item">
        <Icon name="target" size="sm" />
        <div>
          <strong>PTR Names:</strong> Generated by reversing IP octets/nibbles and appending the appropriate arpa domain.
        </div>
      </div>
      <div class="overview-item">
        <Icon name="file" size="sm" />
        <div>
          <strong>Zone Lines:</strong> Ready-to-use DNS zone file entries with proper PTR record format.
        </div>
      </div>
    </div>
  </div>

  <!-- Examples Card -->
  <div class="card examples-card">
    <details class="examples-details">
      <summary class="examples-summary">
        <Icon name="chevron-right" size="sm" />
        <h3>Quick Examples</h3>
      </summary>
      <div class="examples-grid">
        {#each examples as example (example.label)}
          <button
            class="example-card {selectedExample === example.label ? 'active' : ''}"
            onclick={() => loadExample(example)}
          >
            <div class="example-header">
              <div class="example-label">{example.label}</div>
              <div class="example-type {example.type}">
                {example.type === 'single' ? 'Single IP' : 'CIDR Block'}
              </div>
            </div>
            <code class="example-input">{example.input}</code>
            <div class="example-description">{example.description}</div>
          </button>
        {/each}
      </div>
    </details>
  </div>

  <!-- Input Card -->
  <div class="card input-card">
    <!-- Input Type Selection -->
    <div class="type-section">
      <h3 class="type-label">Input Type</h3>
      <div class="type-options">
        <label class="type-option">
          <input type="radio" bind:group={inputType} value="single" onchange={handleTypeChange} />
          <div class="type-content">
            <Icon name="target" size="sm" />
            <span>Single IP</span>
          </div>
        </label>
        <label class="type-option">
          <input type="radio" bind:group={inputType} value="cidr" onchange={handleTypeChange} />
          <div class="type-content">
            <Icon name="network" size="sm" />
            <span>CIDR Block</span>
          </div>
        </label>
      </div>
    </div>

    <!-- IP/CIDR Input -->
    <div class="input-group">
      <label
        for="ip-input"
        use:tooltip={inputType === 'single'
          ? 'Enter a single IPv4 or IPv6 address'
          : 'Enter an IPv4 or IPv6 CIDR block (e.g., 192.168.1.0/24)'}
      >
        <Icon name={inputType === 'single' ? 'target' : 'network'} size="sm" />
        {inputType === 'single' ? 'IP Address' : 'CIDR Block'}
      </label>
      <input
        id="ip-input"
        type="text"
        bind:value={inputValue}
        oninput={handleInputChange}
        placeholder={inputType === 'single' ? '192.168.1.100 or 2001:db8::1' : '192.168.1.0/24 or 2001:db8::/64'}
        class="ip-input {results?.success === true ? 'valid' : results?.success === false ? 'invalid' : ''}"
        spellcheck="false"
      />
    </div>
  </div>

  <!-- Results Card -->
  {#if results && inputValue.trim()}
    <div class="card results-card">
      {#if results.success}
        <div class="results-header">
          <h3>PTR Records Generated</h3>
          <div class="summary-stats">
            <div class="stat-item">
              <span class="stat-value">{results.summary.totalEntries}</span>
              <span class="stat-label">Total PTRs</span>
            </div>
            {#if results.summary.ipv4Entries > 0}
              <div class="stat-item">
                <span class="stat-value">{results.summary.ipv4Entries}</span>
                <span class="stat-label">IPv4</span>
              </div>
            {/if}
            {#if results.summary.ipv6Entries > 0}
              <div class="stat-item">
                <span class="stat-value">{results.summary.ipv6Entries}</span>
                <span class="stat-label">IPv6</span>
              </div>
            {/if}
            <div class="stat-item">
              <span class="stat-value">{results.summary.uniqueZones}</span>
              <span class="stat-label">Zones</span>
            </div>
          </div>
        </div>

        <!-- PTR Records Table -->
        <div class="ptr-records">
          <h4>
            <Icon name="list" size="sm" />
            PTR Records & Zone Lines
          </h4>
          <div class="records-table">
            <div class="table-header">
              <div class="col-ip">IP Address</div>
              <div class="col-ptr">PTR Record Name</div>
              <div class="col-zone-line">Zone File Line</div>
              <div class="col-type">Type</div>
            </div>
            {#each results.entries.slice(0, 100) as entry (`${entry.ip}-${entry.ptrName}`)}
              <div class="table-row">
                <div class="col-ip">
                  <code>{entry.ip}</code>
                </div>
                <div class="col-ptr">
                  <code>{entry.ptrName}</code>
                  <button
                    class="copy-button {clipboard.isCopied(`ptr-${entry.ip}`) ? 'copied' : ''}"
                    onclick={() => clipboard.copy(entry.ptrName, `ptr-${entry.ip}`)}
                  >
                    <Icon name={clipboard.isCopied(`ptr-${entry.ip}`) ? 'check' : 'copy'} size="sm" />
                  </button>
                </div>
                <div class="col-zone-line">
                  {#snippet zoneLine()}
                    {@const recordName = entry.ptrName.replace(`.${entry.zone}`, '').replace(/\.$/, '')}
                    {@const hostname = `host-${entry.ip.replace(/[:.]/g, '-')}.example.com.`}
                    <code>{recordName} IN PTR {hostname}</code>
                  {/snippet}
                  {@render zoneLine()}
                  <button
                    class="copy-button {clipboard.isCopied(`zone-${entry.ip}`) ? 'copied' : ''}"
                    onclick={() => {
                      const recordName = entry.ptrName.replace(`.${entry.zone}`, '').replace(/\.$/, '');
                      const hostname = `host-${entry.ip.replace(/[:.]/g, '-')}.example.com.`;
                      clipboard.copy(`${recordName}    IN    PTR    ${hostname}`, `zone-${entry.ip}`);
                    }}
                  >
                    <Icon name={clipboard.isCopied(`zone-${entry.ip}`) ? 'check' : 'copy'} size="sm" />
                  </button>
                </div>
                <div class="col-type">
                  <span class="type-badge {entry.type.toLowerCase()}">{entry.type}</span>
                </div>
              </div>
            {/each}
            {#if results.entries.length > 100}
              <div class="table-truncated">
                ... and {results.entries.length - 100} more records
              </div>
            {/if}
          </div>
        </div>
      {:else}
        <div class="error-result">
          <Icon name="alert-triangle" size="lg" />
          <h4>Generation Error</h4>
          <p>{results.error}</p>
          <div class="error-help">
            <strong>Valid formats:</strong>
            <ul>
              <li>Single IPv4: 192.168.1.100</li>
              <li>Single IPv6: 2001:db8::1</li>
              <li>IPv4 CIDR: 192.168.1.0/24 (max /16)</li>
              <li>IPv6 CIDR: 2001:db8::/64 (max /64)</li>
            </ul>
          </div>
        </div>
      {/if}
    </div>
  {/if}

  <!-- Educational Content Card -->
  <div class="education-card">
    <div class="education-grid">
      <div class="education-item info-panel">
        <h4>PTR Record Format</h4>
        <p>
          PTR records use the special <code>in-addr.arpa</code> (IPv4) and <code>ip6.arpa</code> (IPv6) domains. IP
          addresses are reversed: <code>192.168.1.100</code> becomes <code>100.1.168.192.in-addr.arpa</code>.
        </p>
      </div>

      <div class="education-item info-panel">
        <h4>Zone File Usage</h4>
        <p>
          The generated zone file lines can be copied directly into your reverse DNS zone files. Remember to adjust the
          hostname targets to match your actual domain structure.
        </p>
      </div>

      <div class="education-item info-panel">
        <h4>IPv6 Nibbles</h4>
        <p>
          IPv6 PTR records use individual hex digits (nibbles) reversed. Each character becomes a separate label: <code
            >2001:db8::1</code
          >
          becomes a very long <code>ip6.arpa</code> name.
        </p>
      </div>

      <div class="education-item info-panel">
        <h4>Best Practices</h4>
        <p>
          Ensure PTR records have corresponding A/AAAA records for proper forward-reverse DNS consistency. Use
          descriptive hostnames that include IP information for easier network management.
        </p>
      </div>
    </div>
  </div>
</div>

<style lang="scss">
  .info-card {
    margin-bottom: var(--spacing-xl);
  }

  .overview-content {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-xs);
  }

  .overview-item {
    display: flex;
    align-items: flex-start;
    gap: var(--spacing-sm);
    color: var(--text-secondary);

    code {
      background-color: var(--bg-tertiary);
      color: var(--text-primary);
      padding: 2px var(--spacing-xs);
      border-radius: var(--radius-sm);
      font-family: var(--font-mono);
    }

    strong {
      color: var(--text-primary);
    }
  }

  .examples-card {
    margin-bottom: var(--spacing-xl);
    padding: 0;
  }

  .examples-details {
    border: none;
    background: none;

    &[open] {
      .examples-summary :global(.icon) {
        transform: rotate(90deg);
      }
    }
  }

  .examples-summary {
    display: flex;
    align-items: center;
    gap: var(--spacing-xs);
    padding: var(--spacing-md);
    cursor: pointer;
    list-style: none;
    user-select: none;
    transition: all var(--transition-fast);
    border-radius: var(--radius-md);

    &:hover {
      background-color: var(--surface-hover);
    }

    &::-webkit-details-marker {
      display: none;
    }

    :global(.icon) {
      transition: transform var(--transition-fast);
    }

    h3 {
      margin: 0;
      font-size: var(--font-size-md);
    }
  }

  .examples-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: var(--spacing-sm);
    padding: var(--spacing-md);
  }

  .example-card {
    padding: var(--spacing-md);
    background-color: var(--bg-secondary);
    border: 1px solid var(--border-primary);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: all var(--transition-fast);
    text-align: left;
    display: flex;
    flex-direction: column;
    gap: var(--spacing-xs);

    &:hover {
      background-color: var(--surface-hover);
      border-color: var(--border-primary);
      transform: translateY(-1px);
    }

    &.active {
      background-color: var(--surface-hover);
      border-color: var(--border-primary);
      box-shadow: var(--shadow-md);
    }
  }

  .example-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-xs);
  }

  .example-label {
    font-weight: 600;
    color: var(--text-primary);
    font-size: var(--font-size-sm);
  }

  .example-type {
    font-size: var(--font-size-xs);
    padding: 2px var(--spacing-xs);
    border-radius: var(--radius-sm);
    font-weight: 600;

    &.single {
      background-color: rgba(34, 197, 94, 0.1);
      color: var(--color-success);
    }

    &.cidr {
      background-color: rgba(59, 130, 246, 0.1);
      color: var(--color-primary);
    }
  }

  .example-input {
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    color: var(--text-primary);
    background-color: var(--bg-tertiary);
    padding: var(--spacing-xs);
    border-radius: var(--radius-sm);
    word-break: break-all;
  }

  .example-description {
    font-size: var(--font-size-xs);
    color: var(--text-secondary);
  }

  .input-card {
    margin-bottom: var(--spacing-xl);
  }

  .type-section {
    margin-bottom: var(--spacing-lg);
  }

  .type-label {
    display: block;
    margin-bottom: var(--spacing-sm);
    font-weight: 600;
    color: var(--text-primary);
    font-size: var(--font-size-md);
  }

  .type-options {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: var(--spacing-md);
  }

  .type-option {
    position: relative;
    cursor: pointer;

    input[type='radio'] {
      position: absolute;
      opacity: 0;
      pointer-events: none;
    }

    .type-content {
      display: flex;
      align-items: center;
      gap: var(--spacing-sm);
      padding: var(--spacing-md);
      background-color: var(--bg-secondary);
      border: 2px solid var(--border-primary);
      border-radius: var(--radius-md);
      transition: all var(--transition-fast);
      font-weight: 600;
      color: var(--text-primary);
    }

    &:hover .type-content {
      background-color: var(--surface-hover);
      border-color: var(--border-primary);
    }

    input[type='radio']:checked + .type-content {
      background-color: var(--surface-hover);
      border-color: var(--color-primary);
      box-shadow: 0 0 0 3px rgba(var(--color-primary-rgb), 0.1);
    }
  }

  .input-group {
    margin-bottom: var(--spacing-lg);

    label {
      display: flex;
      align-items: center;
      gap: var(--spacing-xs);
      margin-bottom: var(--spacing-sm);
      font-weight: 600;
      color: var(--text-primary);
      font-size: var(--font-size-md);
    }
  }

  .ip-input {
    width: 100%;
    padding: var(--spacing-md) var(--spacing-lg);
    font-size: var(--font-size-lg);
    font-family: var(--font-mono);
    border: 2px solid var(--border-primary);
    border-radius: var(--radius-lg);
    background-color: var(--bg-secondary);
    color: var(--text-primary);
    transition: all var(--transition-fast);

    &:focus {
      outline: none;
      border-color: var(--border-primary);
      box-shadow: 0 0 0 3px rgba(var(--color-primary-rgb), 0.1);
    }

    &.valid {
      border-color: var(--color-success);
    }

    &.invalid {
      border-color: var(--color-error);
    }
  }

  .results-card {
    margin-bottom: var(--spacing-xl);
  }

  .results-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-lg);

    @media (max-width: 768px) {
      flex-direction: column;
      gap: var(--spacing-md);
    }

    h3 {
      display: flex;
      align-items: center;
      gap: var(--spacing-xs);
      margin: 0;
    }
  }

  .summary-stats {
    display: flex;
    gap: var(--spacing-lg);
  }

  .stat-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--spacing-xs);
  }

  .stat-value {
    font-size: var(--font-size-xl);
    font-weight: 700;
    color: var(--text-primary);
  }

  .stat-label {
    font-size: var(--font-size-sm);
    color: var(--text-secondary);
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .ptr-records {
    margin-bottom: var(--spacing-xl);

    h4 {
      display: flex;
      align-items: center;
      gap: var(--spacing-xs);
      margin-bottom: var(--spacing-md);
    }
  }

  .records-table {
    border: 1px solid var(--border-primary);
    border-radius: var(--radius-lg);
    overflow: hidden;
  }

  .table-header,
  .table-row {
    display: grid;
    grid-template-columns: 1fr 1.5fr 2fr auto;
    gap: var(--spacing-md);
    padding: var(--spacing-md);
    align-items: center;
  }

  .table-header {
    background-color: var(--bg-secondary);
    font-weight: 600;
    color: var(--text-primary);
    border-bottom: 1px solid var(--border-primary);
  }

  .table-row {
    border-bottom: 1px solid var(--border-secondary);

    &:last-child {
      border-bottom: none;
    }

    &:hover {
      background-color: var(--surface-hover);
    }
  }

  .col-ptr,
  .col-zone-line {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);

    code {
      font-size: var(--font-size-xs);
      word-break: break-all;
    }
  }

  .copy-button {
    background: none;
    border: none;
    color: var(--text-secondary);
    cursor: pointer;
    padding: var(--spacing-xs);
    border-radius: var(--radius-sm);
    transition: all var(--transition-fast);
    flex-shrink: 0;

    &:hover {
      background-color: var(--surface-hover);
      color: var(--text-primary);
    }

    &.copied {
      color: var(--color-success);
    }
  }

  .type-badge {
    font-size: var(--font-size-xs);
    padding: 2px var(--spacing-xs);
    border-radius: var(--radius-sm);
    font-weight: 600;

    &.ipv4 {
      background-color: rgba(34, 197, 94, 0.1);
      color: var(--color-success);
    }

    &.ipv6 {
      background-color: rgba(147, 51, 234, 0.1);
      color: var(--color-accent);
    }
  }

  .table-truncated {
    padding: var(--spacing-md);
    text-align: center;
    color: var(--text-secondary);
    font-style: italic;
    background-color: var(--bg-secondary);
  }

  .error-result {
    text-align: center;
    padding: var(--spacing-xl);
    background-color: var(--bg-secondary);
    border: 1px solid var(--color-error);
    border-radius: var(--radius-lg);
    color: var(--color-error-light);

    :global(.icon) {
      color: var(--color-error);
      margin-bottom: var(--spacing-md);
    }

    h4 {
      margin-bottom: var(--spacing-md);
    }

    p {
      margin-bottom: var(--spacing-lg);
    }
  }

  .error-help {
    text-align: left;
    background-color: var(--bg-tertiary);
    padding: var(--spacing-md);
    border-radius: var(--radius-md);
    color: var(--text-secondary);

    ul {
      margin-top: var(--spacing-sm);
      padding-left: var(--spacing-lg);

      li {
        margin-bottom: var(--spacing-xs);
        font-family: var(--font-mono);
        font-size: var(--font-size-sm);
      }
    }
  }

  .education-card {
    border-top: 1px solid var(--border-secondary);
    padding-top: var(--spacing-xl);
  }

  .education-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: var(--spacing-lg);
  }

  .education-item {
    padding: var(--spacing-lg);
    background-color: var(--bg-secondary);
    border: 1px solid var(--border-primary);
    border-radius: var(--radius-lg);

    h4 {
      display: flex;
      align-items: center;
      gap: var(--spacing-xs);
      margin-bottom: var(--spacing-md);
      font-size: var(--font-size-md);
      color: var(--color-primary);
    }

    p {
      color: var(--text-secondary);
      line-height: 1.6;
      margin: 0;
    }

    code {
      background-color: var(--bg-tertiary);
      color: var(--text-primary);
      padding: 2px var(--spacing-xs);
      border-radius: var(--radius-sm);
      font-family: var(--font-mono);
    }
  }

  @media (max-width: 768px) {
    .examples-grid {
      grid-template-columns: 1fr;
    }

    .type-options {
      grid-template-columns: 1fr;
    }

    .summary-stats {
      flex-direction: column;
      gap: var(--spacing-md);
    }

    .table-header,
    .table-row {
      grid-template-columns: 1fr;
      gap: var(--spacing-sm);
      font-size: var(--font-size-sm);
    }

    .col-zone-line {
      order: 3;

      code {
        font-size: var(--font-size-xs);
      }
    }

    .education-grid {
      grid-template-columns: 1fr;
    }
  }
</style>
